name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: test slua
      run: |
        # !! no leading tabs here - spaces only !!
        set -e
        set -v
        # build only sglua (musl libc not available) 
        make sglua
        ./sglua test/test_luazen.lua
        # install musl, build static slua 
        sudo apt install musl musl-tools
        make clean 
        make slua
        ./slua test/test_luazen.lua
